#pragma once
#include <windows.h>
#include <cstdint>
#include <Psapi.h>
#include <vector>
#include <locale>
#include <String>
#include <d3d11.h>
#include <iostream>
#include <fstream>
using namespace std;
#include "Imgui/imgui.h"
#include "Imgui/imgui_impl_dx11.h"
#include "Imgui/imgui_impl_win32.h"
#include "Macro.h"
#include "XorStr.h"
#include "Fonts.h"
#include "MemoryHelper.h"
#include "ReturnSpoofer.h"
#include "SDKVector.h"
#include "SDKUnRealEngine.h"
#include "Settings.h"
#include "DiscordHelper.h"
#include "RenderHelper.h"
#include "EngineHelper.h"
#include "CheatAimbot.h"
#include "HookNoKick.h"
#include "HookCalculateShot.h"
#include "HookProcessEvent.h"
#include "HookGetViewPoint.h"
#include "CheatESP.h"
#include "Spfr2.h"
#include "CheatManipulation.h"
#include "RenderCore.h"
